#!/usr/bin/env bash
#
# Copyright © 2010-2023 OddSource Code (license@oddsource.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

>&2 echo "Wrapping Python command as follows to enable Address Sanitizer:"

if uname -a 2>&1 | grep -i "darwin" > /dev/null
then
  DYLD_INSERT_LIBRARIES="$(clang -print-file-name=libclang_rt.asan_osx_dynamic.dylib)"
  export DYLD_INSERT_LIBRARIES
  export ASAN_OPTIONS=detect_stack_use_after_return=1:verify_asan_link_order=0

  >&2 echo "export DYLD_INSERT_LIBRARIES='${DYLD_INSERT_LIBRARIES}'"
else
  LD_PRELOAD="$(realpath "$(gcc -print-file-name=libasan.so)") $(realpath "$(gcc -print-file-name=libstdc++.so)")"
  export LD_PRELOAD
  export LSAN_OPTIONS=print_suppressions=1:suppressions=build/lsan-suppressions.txt
  export ASAN_OPTIONS=detect_stack_use_after_return=1:detect_leaks=1:verify_asan_link_order=0

  >&2 echo "export LD_PRELOAD='${LD_PRELOAD}'"
  >&2 echo "export LSAN_OPTIONS='${LSAN_OPTIONS}'"
fi

>&2 echo "export ASAN_OPTIONS='${ASAN_OPTIONS}'"
>&2 echo "exec python -m" "$@"
>&2 echo

exec python "$@"
