#!/usr/bin/env bash
#
# Copyright © 2010-2026 OddSource Code (license@oddsource.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS:BOOL=ON -DENABLE_ADDRESS_SANITIZER:BOOL=ON -S . -B ./cmake-build-test-with-asan
cmake --build ./cmake-build-test-with-asan --config Debug -j 14

if uname -a 2>&1 | grep -i "darwin" > /dev/null
then
  export ASAN_OPTIONS=detect_stack_use_after_return=1:verify_asan_link_order=0
  export MallocNanoZone=0
else
  export ASAN_OPTIONS=detect_stack_use_after_return=1:detect_leaks=1:verify_asan_link_order=0
fi

echo "#######################################"
echo "#  Running ASAN shared library tests  #"
echo "#######################################"
./cmake-build-test-with-asan/ifaddrs4cpp_shared_tests
echo

echo "#######################################"
echo "#  Running ASAN static library tests  #"
echo "#######################################"
./cmake-build-test-with-asan/ifaddrs4cpp_static_tests
