#
# Copyright © 2010-2023 OddSource Code (license@oddsource.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: "Address Sanitizer Analysis"

on:
  pull_request:
  push:
  schedule:
    - cron: "0 1 * * SUN"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    permissions:
      actions: read  # for github/codeql-action/init to get workflow details
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/analyze to upload SARIF results
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-20.04, ubuntu-22.04]
        java: ["17", "21"]
        include:
          - java: "17"
            python: "3.9"
          - java: "21"
            python: "3.11"
          - os: macos-13
            asan_options: detect_stack_use_after_return=1:verify_asan_link_order=0
          - os: ubuntu-20.04
            asan_options: detect_stack_use_after_return=1:detect_leaks=1:verify_asan_link_order=0
          - os: ubuntu-22.04
            asan_options: detect_stack_use_after_return=1:detect_leaks=1:verify_asan_link_order=0
    runs-on: ${{ matrix.os }}
    name: "ASAN on ${{ matrix.os }} / Java ${{ matrix.java }} / Python ${{ matrix.python }}"
    steps:
      - name: Checkout ifaddrs4u
        uses: actions/checkout@v4

      - name: Installing CMake
        uses: lukka/get-cmake@latest

      - name: CMake Prepare
        working-directory: ifaddrs4cpp
        shell: bash
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS:BOOL=ON -DENABLE_ADDRESS_SANITIZER:BOOL=ON -S . -B ./cmake-debug-test-build

      - name: Compile ifaddrs4cpp Debug
        working-directory: ifaddrs4cpp
        shell: bash
        run: cmake --build ./cmake-debug-test-build --config Debug -j 14

      - name: Run ifaddrs4cpp Tests
        working-directory: ifaddrs4cpp
        shell: bash
        env:
          ASAN_OPTIONS: "${{ matrix.asan_options }}"
        run: ./cmake-debug-test-build/ifaddrs4cpp_tests

      - name: Installing Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "${{ matrix.java }}"
          java-package: "jdk"
          cache: "maven"

      - name: Installing Maven 3.9.5
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.5

      - name: Build ifaddrs4j with Maven
        working-directory: ifaddrs4j
        shell: bash
        run: |
             echo -e "java = $(which java)\njavac = $(which javac)\nJAVA_HOME = $JAVA_HOME"
             mvn -B --version
             mvn -B -P cpp-asan -P cpp-debug '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn' help:active-profiles install
